profiles/urls.py
from django.urls import path, re_path

from .views import (
	signup, ProfileUpdateView, account_activation_sent_view, account_activate
)

app_name = 'core'

urlpatterns = [
	path('', signup, name='profile-signup'),
	path('<int:pk>/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

urlpatterns += [
	path('account-activation-sent/', account_activation_sent_view, name='account-activation-sent'),
	path('activate/<uidb64>/<token>/',
		account_activate, name='activate'),
]

users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view, rewards_view,shop_details_view, sastakaam,garbage

app_name = "users"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('rewards/', rewards_view, name='rewards'),
    path('shopdetails/',shop_details_view,name='shopdetails'),
    path('showresult/', sastakaam, name='plastic_processing' ),
    path('garbage/', garbage, name='script_processing' )
    
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	username = forms.CharField(
		label='',
		max_length=30,
		min_length=5,
		required=True,
		widget=forms.TextInput(
			attrs={
				"placeholder": "Username",
				"class": "form-control"
			}
		)
	)

	email = forms.EmailField(
		label='',
		max_length=255,
		required=True,
		widget=forms.EmailInput(
			attrs={
				"placeholder": "Email",
				"class": "form-control"
			}
		)
	)

	password1 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Password",
				"class": "form-control"
			}
		)
	)

	password2 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Confirm Password",
				"class": "form-control"
			}
		)
	)

	location = forms.CharField(
		label='',
		max_length=30,
		required=False,
		widget=forms.HiddenInput(
			attrs={
				"display": "none"
			}
		)
	)

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2', 'location')

templates/app/dashboard.html
{% extends "base_dashboard.html" %}
{% load static %}
{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ messages }}</p>
		    </div>
		</div>
		<!--/.Panel-->

	{% endif %}
	{% block graph %}
        <div style="height:70%;width:70%;margin:auto" id="bar_chart">
            {{ bar_chart.as_html }}
        </div>

        <div style="height:70%;width:70%;margin:auto;display:none" id="polar_chart">
            {{ polar_chart.as_html }}
        </div>

        <div style="height:60%;width:50%;margin:auto;display:none" id="pie_chart">
            {{ pie_chart.as_html }}
        </div>
        
	{% endblock %}

    

    {% block plasticVerification %}
        <a class="btn" href="{% url 'users:script_processing' %}">Click here for Garbage Test</a>
        {% comment %} {{ ans }} {% endcomment %}
        <div>
        <img src="{% static 'mldata/plastic105.jpg' %}" alt="Hi!" />
        {% if result %}
            {% if result < 50 %}
                <h1>Our Predicition is that it not plastic.( {{ result }})</h1>
            {% else %}
                <h1> Our Prediction is that it is plastic We are <strong>{{ result }}%<h1> sure about this.</h1>
            {% endif %}
        {% endif %}
        </div>
    {% endblock plasticVerification %}

    {% block prediction %}
            {% if ans %}

                <h1> The predicted type of Garbage is <strong> {{ ans }} </strong> </h1>
                {% if ans == 'plastic' %}
                    <a class="btn" href="{% url 'users:plastic_processing' %}">click for further plastic processing</a>
                {% endif %}
    {% endif %}

    {% endblock prediction%}
        
{% endblock content %}

templates/app/garbage.html
{{ ans }}

templates/app/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	 <h1 class="animated fadeIn mb-4" style="position:absolute;margin-left:20%;margin-top:15%;z-index:10;font-weight:bold;font-size:50px;color:black;">Zero Plastic Automation</h1>
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" style="position:absolute;z-index:2;margin-right:10%;">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="{% static 'img/c2.jpg'%}" alt="First slide">
                {% comment %} <h1 class="animated fadeIn mb-4" style="margin:auto" >Zero Plastic Automation</h1> {% endcomment %}

                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'img/c4.jpg'%}" alt="Second slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'img/c2.jpg'%}" alt="Third slide">
                </div>
              </div>
          </div>

{% endblock content %}

templates/app/mlscript.html
{% extends "base.html" %}


{% block title %}
	Checking script
{% endblock %}

{% block content %}
	{{ target }}
	<div class="text-left mt-5 container">
		Checking Script information here predcition is {{ result }}
	</div>

{% endblock %}

templates/app/profile_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
	Edit Bio
{% endblock %}

{% block content %}
	
	<div class="text-left mt-5 container">
		{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field|attr:"rows:20"|attr:"cols:20" }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		{% endfor %}
	</div>

{% endblock %}

templates/app/rewards.html
{% extends 'base.html' %}

{% block content%}

    <h1> This a Sample Rewards Page</h1>

{% endblock %}

templates/app/shop_details.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-4">
	<!-- Default form register -->
	{% if not form %}
		<h1>ashish</h1>
	{% else %}
	<form class="border mt-5 border-secondary text-center p-3" method="post">
		{% csrf_token %}
		<p class="h4 mb-4 text-secondary text-center">Sign up</p>

		<!-- {{ form.as_p }} -->

		{% for field in form %}
		<p>
			{{ field.label_tag }}
			{{ field }}
			<!-- {% if field.help_text %}
			  <small style="color: grey">{{ field.help_text }}</small>
			{% endif %} -->
			{% for error in field.errors %}
			  <p style="color: red">{{ error }}</p>
			{% endfor %}
		</p>
		{% endfor %}

		<!-- Sign up button -->
		<a class="btn btn-secondary my-4 btn-block" type="submit">Update</a>

		<!-- Social register -->
		<p>or sign up with:</p>

		<a type="button" class="light-blue-text mx-2">
			<i class="fa fa-facebook"></i>
		</a>
		<a type="button" class="light-blue-text mx-2">
			<i class="fa fa-twitter"></i>
		</a>
		<a type="button" class="light-blue-text mx-2">
			<i class="fa fa-linkedin"></i>
		</a>
		<a type="button" class="light-blue-text mx-2">
			<i class="fa fa-github"></i>
		</a>

		<hr>

		<!-- Terms of service -->
		<p>By clicking
			<em>Sign up</em> you agree to our
			<a href="" target="_blank">terms of service</a>
		</p>
	</form>
	{% endif %}
{% endblock %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-4">
<div class="row">
	<div class="col-md-4">
		
		<div class="list-group mt-5">
		    <a href="{% url 'users:home' %}" class="list-group-item list-group-item-action waves-effect">Home</a>
			{% if profile %}
		    <a href="{% url 'profiles:profile-signup' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Profile Sign up
		    	{% else %}
		    	<a href="{% url 'users:sign-up' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Sign up
		    {% endif %}		    	
		    </a>
		    <a href="{% url 'login' %}" class="list-group-item list-group-item-action waves-effect">Login</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Dashboard</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Profile</a>
		</div>

	</div>

		<div class="col-md-2"></div>

	<div class="col-md-4">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    <!-- Social register -->
		    <p>or sign up with:</p>

		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-facebook"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-twitter"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-linkedin"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-github"></i>
		    </a>

		    <hr>

		    <!-- Terms of service -->
		    <p>By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}